puppet_compiler: Add checks for missing facts files
I noticed an issue whith puppet db failing wit the following message

Compiling catalog for achernar.wikimedia.org
Traceback (most recent call last):
  File "/usr/local/bin/puppetdb-populate", line 11, in <module>
    load_entry_point('puppet-compiler==0.5.0', 'console_scripts', 'puppetdb-populate')()
  File "build/bdist.linux-x86_64/egg/puppet_compiler/populate_puppetdb.py", line 55, in main
  File "build/bdist.linux-x86_64/egg/puppet_compiler/utils.py", line 40, in refresh_yaml_date
IOError: [Errno 2] No such file or directory: ''

This happend  because there was a node yaml file but not a facts file

Bug: T228266
Change-Id: Ifd044732cd26a32d14fad30a0ec77ea23f30f240